# Generated by Django 4.2 on 2023-06-21 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0003_alter_person_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="createDate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
