# Generated by Django 4.2 on 2023-06-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0004_person_createdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="file2",
            field=models.FileField(default=2, upload_to="wearable/"),
            preserve_default=False,
        ),
    ]
