# Generated by Django 4.2 on 2023-06-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=20)),
                ("body", models.CharField(max_length=250)),
                ("image", models.ImageField(blank=True, upload_to="image")),
                ("createDate", models.DateTimeField(auto_now_add=True)),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
